# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  request_changes_workflow: true
  auto_review:
    auto_pause_after_reviewed_commits: 0
  pre_merge_checks:
    docstrings:
      mode: off
  tools:
    github-checks:
      enabled: false
