// Generated by the OpenNext build before Wrangler bundles this custom entrypoint.
// @ts-expect-error The generated module is intentionally absent from source control.
import handler from "./.open-next/worker.js";

import { runScheduledBookingRequestExpiry } from "./src/booking-request/booking-request-expiry-schedule";

interface Environment {
  readonly APP_ENVIRONMENT?: string;
  readonly SUPABASE_PROJECT_REF?: string;
  readonly SUPABASE_URL?: string;
  readonly SUPABASE_PUBLISHABLE_KEY?: string;
  readonly SUPABASE_SECRET_KEY?: string;
}

export default {
  fetch: handler.fetch,
  async scheduled(_controller, environment: Environment) {
    await runScheduledBookingRequestExpiry(environment);
  },
} satisfies ExportedHandler<Environment>;
