// Generated by the OpenNext build before Wrangler bundles this custom entrypoint.
// @ts-expect-error The generated module is intentionally absent from source control.
import handler from "./.open-next/worker.js";

import { runScheduledBookingRequestExpiry } from "./src/booking-request/booking-request-expiry-schedule";

import { runScheduledBookingRefunds } from "./src/booking-request/booking-refund-schedule";
import { runScheduledBookingRequestCapture } from "./src/booking-request/booking-request-capture-schedule";
import { runScheduledBookingNotifications } from "./src/notification/notification-schedule";
import { bookingRequestTestRuntimeIsEnabled } from "./src/booking-request/booking-request-test-runtime-core";

interface Environment {
  readonly APP_ENVIRONMENT?: string;
  readonly SUPABASE_PROJECT_REF?: string;
  readonly SUPABASE_URL?: string;
  readonly SUPABASE_PUBLISHABLE_KEY?: string;
  readonly SUPABASE_SECRET_KEY?: string;
}

export default {
  fetch: handler.fetch,
  async scheduled(_controller, environment: Environment) {
    const scheduledTasks: Promise<unknown>[] = [
      runScheduledBookingRequestExpiry(environment),
      runScheduledBookingRequestCapture(environment),
    ];
    if (bookingRequestTestRuntimeIsEnabled(environment))
      scheduledTasks.push(
        runScheduledBookingNotifications(environment),
        runScheduledBookingRefunds(environment),
      );
    const results = await Promise.allSettled(scheduledTasks);
    if (results.some((result) => result.status === "rejected"))
      throw new Error("Scheduled booking-request processing is incomplete");
  },
} satisfies ExportedHandler<Environment>;
