import { defaultExclude, defineConfig } from "vitest/config";

// Only these audited paths have proved they need neither the browser environment nor React setup.
// New or renamed tests stay in the jsdom project until they receive the same review.
const domainNodeTests = [
  "src/access/account-access.test.ts",
  "src/access/actions.test.ts",
  "src/access/privileged-sign-in-audit.test.ts",
  "src/access/request-account-context.test.ts",
  "src/access/return-destination.test.ts",
  "src/access/supabase-account-access.test.ts",
  "src/access/supabase-server.test.ts",
  "src/booking-quote/booking-quote.test.ts",
  "src/booking-quote/supabase-booking-quote.test.ts",
  "src/booking-request/actions.test.ts",
  "src/booking-request/administrator-payment-history.test.ts",
  "src/booking-request/booking-cancellation-policy.test.ts",
  "src/booking-request/booking-cancellation.test.ts",
  "src/booking-request/booking-completion-commands.test.ts",
  "src/booking-request/booking-completion-schedule.test.ts",
  "src/booking-request/booking-completion.test.ts",
  "src/booking-request/booking-financial-presentation.test.ts",
  "src/booking-request/booking-financial-view.test.ts",
  "src/booking-request/booking-lifecycle.test.ts",
  "src/booking-request/booking-management-actions.test.ts",
  "src/booking-request/booking-payout.test.ts",
  "src/booking-request/booking-refund-schedule.test.ts",
  "src/booking-request/booking-refund.test.ts",
  "src/booking-request/booking-request-capture-processing.test.ts",
  "src/booking-request/booking-request-capture-recovery.test.ts",
  "src/booking-request/booking-request-capture-schedule.test.ts",
  "src/booking-request/booking-request-capture.test.ts",
  "src/booking-request/booking-request-confirmation.test.ts",
  "src/booking-request/booking-request-content.test.ts",
  "src/booking-request/booking-request-expiry-schedule.test.ts",
  "src/booking-request/booking-request-lifecycle.test.ts",
  "src/booking-request/booking-request-payment-observation.test.ts",
  "src/booking-request/booking-request-payment-recovery.test.ts",
  "src/booking-request/booking-request-payment-required-expiry.test.ts",
  "src/booking-request/booking-request-policy.test.ts",
  "src/booking-request/booking-request-submission.test.ts",
  "src/booking-request/booking-terms-fixture.test.ts",
  "src/booking-request/confirmed-booking-access.test.ts",
  "src/booking-request/confirmed-booking-history.test.ts",
  "src/booking-request/customer-booking-request.test.ts",
  "src/booking-request/lifecycle-actions.test.ts",
  "src/booking-request/owner-booking-earnings.test.ts",
  "src/booking-request/owner-booking-request-notifications.test.ts",
  "src/booking-request/payment-recovery-actions.test.ts",
  "src/booking-request/request-booking-request-payment-recovery.test.ts",
  "src/booking-request/request-booking-request-submission.test.ts",
  "src/booking-request/request-confirmed-booking-access.test.ts",
  "src/booking-request/request-customer-booking-request.test.ts",
  "src/booking-request/request-owner-booking-request-notifications.test.ts",
  "src/booking-request/supabase-administrator-payment-history.test.ts",
  "src/booking-request/supabase-booking-cancellation.test.ts",
  "src/booking-request/supabase-booking-completion.test.ts",
  "src/booking-request/supabase-booking-lifecycle.test.ts",
  "src/booking-request/supabase-booking-payout.test.ts",
  "src/booking-request/supabase-booking-refund.test.ts",
  "src/booking-request/supabase-booking-request-capture.test.ts",
  "src/booking-request/supabase-booking-request-confirmation.test.ts",
  "src/booking-request/supabase-booking-request-lifecycle.test.ts",
  "src/booking-request/supabase-booking-request-payment-observation.test.ts",
  "src/booking-request/supabase-booking-request-payment-recovery.test.ts",
  "src/booking-request/supabase-booking-request-payment-required-expiry.test.ts",
  "src/booking-request/supabase-booking-request-submission.test.ts",
  "src/ci/client-secret-scan.test.ts",
  "src/ci/workflow.test.ts",
  "src/ci/wrangler.test.ts",
  "src/config/server-environment.test.ts",
  "src/cottage-discovery/discovery-query.test.ts",
  "src/cottage-discovery/supabase-cottage-discovery.test.ts",
  "src/cottage-inventory/actions.test.ts",
  "src/cottage-inventory/cottage-inventory.test.ts",
  "src/cottage-inventory/supabase-cottage-inventory.test.ts",
  "src/cottage-profile/actions.test.ts",
  "src/cottage-profile/cottage-profile.test.ts",
  "src/cottage-profile/owner-cottage-editor.test.ts",
  "src/cottage-profile/supabase-cottage-profile.test.ts",
  "src/cottage-publication/actions.test.ts",
  "src/cottage-publication/cottage-publication-media.test.ts",
  "src/cottage-publication/cottage-publication.test.ts",
  "src/cottage-publication/supabase-cottage-publication.test.ts",
  "src/cottage-shift-schedule/actions.test.ts",
  "src/cottage-shift-schedule/cottage-shift-schedule.test.ts",
  "src/cottage-shift-schedule/supabase-cottage-shift-schedule.test.ts",
  "src/i18n/booking-request-messages.test.ts",
  "src/i18n/booking-request-status-messages.test.ts",
  "src/i18n/format.test.ts",
  "src/i18n/routing.test.ts",
  "src/notification/booking-event-notice.test.ts",
  "src/notification/fictional-notification-adapter.test.ts",
  "src/notification/notification-actions.test.ts",
  "src/notification/notification-delivery.test.ts",
  "src/notification/notification-schedule.test.ts",
  "src/notification/notification-status-repository.test.ts",
  "src/notification/paid-confirmation-notice.test.ts",
  "src/notification/supabase-notification-delivery.test.ts",
  "src/owner-application/actions.test.ts",
  "src/owner-application/owner-application-review.test.ts",
  "src/owner-application/owner-application-status.test.ts",
  "src/owner-application/owner-application.test.ts",
  "src/owner-application/review-actions.test.ts",
  "src/owner-application/supabase-owner-application-review.test.ts",
  "src/owner-application/supabase-owner-application.test.ts",
  "src/payment/booking-refund-contract.test.ts",
  "src/payment/booking-request-capture-contract.test.ts",
  "src/payment/booking-request-payment-recovery-contract.test.ts",
  "src/payment/booking-request-payment-required-expiry-contract.test.ts",
  "src/payment/booking-settlement-contract.test.ts",
  "src/payment/durable-payment-simulator.test.ts",
  "src/payment/payment-contract.test.ts",
  "src/payment/payment-operation-execution.test.ts",
  "src/payment/payment-refund-allocation.test.ts",
  "src/payment/payment-reliability.test.ts",
  "src/translation/call-budget.test.ts",
  "src/translation/configuration.test.ts",
  "src/translation/cottage-publication-translator.test.ts",
  "src/translation/evaluation-cli.test.ts",
  "src/translation/evaluation.test.ts",
  "src/translation/openai-evaluation-runner.test.ts",
  "src/translation/openai-responses.test.ts",
  "src/translation/supabase-translation-store.test.ts",
  "src/translation/translation.test.ts",
] as const;

const allTests = ["src/**/*.test.{ts,tsx}", "scripts/**/*.test.mjs"];

// The board toolkit and git guard under scripts/lib/ are ported verbatim from Flowgauge and
// carry its node:test tests. `npm run test:scripts` runs them and `npm test` chains it after
// this runner, so both suites still run; Vitest must not also collect them, because node:test
// reports through its own runner and would fail here.
const nodeTestScripts = ["scripts/lib/*.test.mjs"];

export default defineConfig({
  resolve: { tsconfigPaths: true },
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: "domain-node",
          environment: "node",
          include: [...domainNodeTests],
        },
      },
      {
        extends: true,
        test: {
          name: "jsdom",
          environment: "jsdom",
          setupFiles: ["./vitest.setup.ts"],
          include: allTests,
          exclude: [...defaultExclude, ...domainNodeTests, ...nodeTestScripts],
        },
      },
    ],
  },
});
